openvenues/libpostal

- resources/dictionaries/en/street_types.txt
NY State has [posted their state address database](http://gis.ny.gov/gisdata/inventories/details.cfm?DSID=921) along with the metadata standards for consuming it. Included in this metadata is a [guide to abbreviations](http://gis.ny.gov/gisdata/supportfiles/Updated-Deliverable-Schema.pdf), incorporated in this pull request.
This adds additional dictionary items for future model trainings.
> Added additional street types from NY State Post-Address Types

- scripts/geodata/osm/fetch_osm_address_data.sh
Using [leisure](http://wiki.openstreetmap.org/wiki/Key:leisure) and [tourism](http://wiki.openstreetmap.org/wiki/Key:tourism) to pull named landmarks like parks, attractions etc. into the OSM training data. No longer requiring addr:housenumber/addr:street as venue + city or venue + neighborhood is sufficient to create examples for the parser.
> Including landmarks + more venues in OSM training data

- README.md
This can cause permission problems otherwise.
The privilege elevation is not required for ~99% of users, as Homebrew's own advice is to install Formulas without `sudo` and therefore most people follow it: https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/FAQ.md#why-does-homebrew-say-sudo-is-bad-
> Do not run Homebrew's brew under sudo

- src/geodb.c
I *think* this is harmless. `setup_parser()` is the only setup function to throw an error if it's called twice before its equivalent teardown function. This stops libpostal from throwing an error if `setup_parser()` has already been called.
```
#include <libpostal/libpostal.h>
int main(int argc, char **argv) {
libpostal_setup();
libpostal_setup_language_classifier();
libpostal_setup_parser();
libpostal_setup_parser();
libpostal_teardown();
libpostal_teardown_language_classifier();
libpostal_teardown_parser();
}
```
> don't error on multiple setup_parser()

- src/Makefile.am
A standard `configure` script allows you to use a separate path for the build simply by calling configure from the directory you want to use as the build directory.
This fix updates Makefile to find the actual libpostal_data file when
`configure` is called from another directory, which it uses as the build
directory.
> Call libpostal_data in source path, not build path

- src/libpostal_data
OpenBSD, for instance, does not have an external `seq` command.
Also this removes trailing white space on eight (8) lines.
> Remove call to `seq` which may not exist

- src/libpostal_data
Resolves https://github.com/openvenues/libpostal/issues/143
> [fix] Use UTC date reference to avoid repeating S3 downloads.

- src/string_utils.c
When using geodb for a country without postal codes, I stumbled on a case where a call to cstring_array_from_char_array with an empty str led to core dump (str->n==0). This patch fixes an issue.
> cstring_array_from_char_array returns NULL for empty char array

- src/matrix.h
Very minor cleanup. I saw this message and had trouble Googling for CLBAS before I realized what it actually meant.
> [fix] typo in compiler warning when no CBLAS found

- src/tagger.h
This fixes a build break on CentOS 6, which has gcc 4.4.7. This was tested using the centos/6 Vagrant box (https://atlas.hashicorp.com/centos/boxes/6).
The specific error message was
```
In file included from crf.h:23,
from address_parser.h:55,
from libpostal.c:10:
tagger.h:5: error: redefinition of typedef ‘tagger_feature_function’
tagger.h:5: note: previous declaration of ‘tagger_feature_function’ was here
```
> [fix] add #include guard to tagger.h

- src/address_parser_train.c
- src/crf_trainer_averaged_perceptron.c
[GCC did not support assigning to unnamed fields from designated initializers until 4.6.](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=10676) Unfortunately, CentOS 6 ships with GCC 4.4, so avoiding this C99 feature is necessary to fix building in CentOS 6 environments.
This patch gets things to build, but I'm open to alternative approaches to fixing the build. I'm hoping that the compiler is smart enough to see that this should result in effectively the same assembly code that the previous approach did.
> [fix] don't use unnamed fields in initializers

- .travis.yml
- src/Makefile.am
- src/libpostal.c
- src/normalize.c
- src/normalize.h
- src/numex.c
- src/numex.h
- src/numex_table_builder.c
In some address data sets, it's common to see things like "E 96 St" instead of "E 96th St" as might appear on a street sign.
We have ordinal suffixes in libpostal's numeric expression configs, but so far they've only been used to add the correct suffix when parsing ordinal expressions like "One hundred twenty-third". Using the rule sets, we can get to the number "123". For ordinals, we then have a trie that maps final digits to their correct suffix ("3" => "rd" unless preceded by a "1" such that "13" => "th").
This PR adds another type of trie entry to the numex table which allows us to look up whether the current token is an ordinal (digits + a valid suffix in the language/s being considered). We can then add a form of the string to the expansions with the ordinal suffix removed. This is …
> Remove ordinal suffixes in libpostal_expand_address

- src/libpostal.c
Hi 
There are quite a few compiler warnings with the current Makefile settings. This patch fixes 10 of them.
I hope to be able to contribute more fixes based on the compiler warnings, which should make any new warnings which come up more visible - making the warnings more useful.
Thanks
Iestyn
> Fix log_debug formats which expect unsigned int but receive size_t

- src/trie_search.c
- src/trie_utils.c
Hi - a little more cleanup of log_{debug,info} messages.
> Fix log_{debug,info} formats which expect size_t but receive int.

- README.md
Hi maintainers,
We recently opensourced a [Elixir binding for libpostal](https://github.com/SweetIQ/expostal). The binding is well documented and tested against libpostal master branch. Hoping to add this to the project README for better visibility.
> Add Elixir language binding to README.md

- src/numex.c
There are a few more cases that can smash the stack on 32-bit machines when reading 64-bit ints into `enum` types in numex.c. Reading the on-disk values into a local uint64, then casting.
> 32-bit safety in numex table loading

- resources/addresses/is.yaml
The front matter of the is.yaml says it is the danish description, but it is not. It is the icelandic description.
> Changes front matter of iis.yaml to correct description

- src/log/log.h
The bash color codes in the log messages don't work for Windows and result in strange characters being printed to the console.  I've put together a pull request to default windows builds to `LOG_NO_COLORS` mode.  I've also merged the `log_debug()` function into the other declarations a bit neater.
> Removing console colors for Windows builds

- src/address_parser.c
This leak can be reproduced with:
```c
libpostal_address_parser_options_t options = { .country = "US", .language = "en"};
libpostal_address_parser_response_t *parsed = libpostal_parse_address("foo", options);
libpostal_address_parser_response_destroy(parsed);
```
The normalized value was not freed before an early return.
Here was the relevant output from Valgrind before the fix:
```
==17267== 4 bytes in 1 blocks are definitely lost in loss record 1 of 279
==17267==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==17267==    by 0x146897: utf8proc_map (utf8proc.c:608)
==17267==    by 0x146B3D: normalize_string_utf8_languages (normalize.c:69)
==17267==    by 0x146D4C: normalize_string_latin_languages (normalize.c:128)
==17267==    by 0x14FD8A: …
```
> Fix leak of normalized value in early return

- scripts/geodata/polygons/reverse_geocode.py
Hi,
I corrected a small typo that made the python script impossible to run.
I'll use this PR to ask a question.
I want to create an easier way to use the osm administrative regions. I'm trying to create a admin hierarchy a bit like WoF but based only on OSM (and maybe quattroshapes) , with typed zones that depends on each other (I've described this in [a repo](https://github.com/QwantResearch/cosmogony))
When I found libpostal python scripts I though they would be a perfect starting point, but I find those very difficult to use.
Are those scripts still used ?
Do you have some documentation or code on how you use the scripts to generate the training dataset ?
I'm a bit lost on which script I need to call and with which parameters (and I have some small problems like this PR when running …
> Fix typo in python imports

- src/soft_tfidf.c
Initialize local arrays suffixes1 and suffixes2 in function soft_tfidf_similarity_with_phrases_and_acronyms explicitly with NULL in order to prevent segmentation faults due to undefined initial values if ordinal_suffixes1 and ordinal_suffixes2 are NULL.
> Fix segmentation fault in soft_tfidf.c

- src/geohash/geohash.c
Add missing bit shifts in the function geohashstr_to_interleaved in order to be able to calculate correctly the  
1) geo coordinates from a given geohash and 
2) neigbor geohashes of a given geohash.
The incorrect calculation of neighbor geohashes e.g. has the following impact on the deduplication with lieu: Features are compared that should not be compared because they are too far away from each other. This often results in distances between duplicates that exceed by far the max. expected distance according to the used geohash precision.
> Fix a bug in file geohash/geohash.c

- README.md
Adds a link to the Rust bindings I have been working on. See more [here](https://github.com/kodemartin/rustpostal).
> Add rustpostal to unofficial bindings

- README.md
M1 Macs don't support x86/Intel SSE2 instructions (see #551). This adds the workaround to get libpostal to build to the README.
> build instructions for M1 macs (see #551)

- src/matrix.h
I'm building libpostal in an environment without autotools, and it's been very helpful that I can just pass the necessary `-D` flags to avoid needing an autoconf-generated `config.h`. However, this check wasn't applied in `matrix.h`.
> Check HAVE_CONFIG_H in matrix.h

- README.md
- configure.ac
- src/crf_context.c
- src/sse2neon.h
- src/vector_math.h
- test/Makefile.am
- windows/configure.ac
I've added https://github.com/DLTcollab/sse2neon so the code stays almost the same and the configure process will pick the best flags based on architecture.
The default config will use either SSE2 or NEON (based on processor architecture).
The hardware optimizations can be disabled by passing `--disable-sse2` and `--disable-neon` to `./configure`.
I was able to run the test suite on one of my projects that uses libpostal extensively with no problems. For my use case there was no speedup so I couldn't verify that the NEON instructions speed anything up.
Resolves https://github.com/openvenues/libpostal/issues/433.
Resolves https://github.com/openvenues/libpostal/issues/551.
> Use NEON on ARM hardware via sse2neon.h

- README.md
The `make` command fails when run *before* `configure`, this is confusing users which are not familiar with `automake`.
```bash
make distclean
make: *** No rule to make target `distclean'.  Stop.
make
make: *** No targets specified and no makefile found.  Stop.
```
resolves https://github.com/openvenues/libpostal/issues/595
> Makefile is not available until after configure

- README.md
The `make distclean` command is not required in this example, which is a fresh clone
related: https://github.com/openvenues/libpostal/pull/605#issuecomment-1295954750
> docs: remove make distclean

- m4/ax_cblas.m4
Hi 👋 
I'd like to compile using [`libopenblas-openmp-dev`](https://packages.debian.org/search?searchon=names&keywords=libopenblas-openmp-dev). OpenBLAS is still [actively](https://www.openblas.net/Changelog.txt) maintained and has optional OpenMP support. In [comparison](https://wiki.debian.org/DebianScience/LinearAlgebraLibraries), the latest ATLAS release is from 2016.
Currently, `cblas_dgemm` will be [recognized](https://github.com/ddelange/libpostal-fastapi/actions/runs/4730353072/jobs/8393956993#step:7:897) but [not used](https://github.com/ddelange/libpostal-fastapi/actions/runs/4730353072/jobs/8393956993#step:7:1116).
This PR [fixes](https://github.com/ddelange/libpostal-fastapi/actions/runs/4730639843/jobs/8395560580#step:7:1026) that.
> Add support for OpenBLAS

- src/file_utils.c
unsigned char* gets promoted to `int`, which cannot always be shifted by 24 bits.
Justine Tunney blogs about it here: https://justine.lol/endian.html
Example:
```deserialize.c
#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>
uint32_t file_deserialize_uint32_ok(unsigned char *buf) {
return ((uint32_t)buf[0] << 24) | ((uint32_t)buf[1] << 16) | ((uint32_t)buf[2] << 8) | (uint32_t)buf[3];
}
uint32_t file_deserialize_uint32(unsigned char *buf) {
return (buf[0] << 24) | (buf[1] << 16) | (buf[2] << 8) | buf[3];
}
int main() {
unsigned char arr[4] = {0xaa, 0xaa, 0xaa, 0xaa};
printf("%d\n", file_deserialize_uint32_ok((unsigned char*)arr));
printf("%d\n", file_deserialize_uint32((unsigned char*)arr));
}
```
Output:
```
$ clang-16 -fsanitize=undefined ./deserialize.c -o deserialize && …
```
> avoid UB in bit shifts

- src/libpostal_data.in
Fix the syntax error reported by dash:
./src/libpostal_data: 39: [: ==: unexpected operatora
when the variable DATAMODEL is empty.
> Fix dash syntax error in libpostal_data

- .github/workflows/test.yml
- README.md
- configure.ac
- src/crf_context.c
- src/vector.h
- src/vector_math.h
- test/Makefile.am
- windows/configure.ac
from #597 #592 and #578 there's an issue in the memory alignment boundary when running the tests with SSE and the remez algorithm which is looping over 4 doubles (it uses 16 bytes in a few places for defining some constants but should actually be guaranteed to be aligned to 32 bytes) and the crf_context test calls for 3x3 labels which can create undefined behavior. It strangely hasn't shown up previously and shouldn't in normal parser usage but that's only because the parser happens to have L=20 labels and the CRF's context matrix is L x L x T, so for any number of items T, it's always aligning something proportional to 4.
Trying this piece out first with the new Github Actions build, then will add a standards-compliant implementation of an aligned realloc.
> fixes for SSE/memalign issue in crf_context test

- README.md
@albarrentine can this get some love?
1) There was a package missing from the Ubuntu requirements: `build-essential`. I added it.
2) I show 3 common configuration options: x86, Macs and the Senzing data model
> Update README.md to include 'build-essential' package in apt list and 3 common configuration options

- .github/workflows/test.yml
- configure.ac
SSE is not available on arm64, so the fact that we pass these flags causes compilation errors...
> Do not use SSE flags on arm64 platform

- src/expand.c
- src/language_classifier.c
- src/language_classifier.h
- src/language_classifier_cli.c
- src/language_classifier_test.c
- src/libpostal.c
- src/near_dupe.c
- src/place.c
- src/place.h
- src/sparse_matrix_utils.c
PR #465 redefined the language classifier response struct in the API and was casting between incompatible pointer types. Using the exported struct everywhere, similar to what we do for `parse_address`.
> Using exported libpostal_language_classifier_response_t struct throughout, fixes #677

- README.md
- Remove duplicate reference and squash unofficial headers
- Clarify postgresql extension is unofficial
- Add [`libpostal-fastapi`](https://github.com/alpha-affinity/libpostal-fastapi) to the unofficial servers
[rendered link](https://github.com/openvenues/libpostal/blob/ef215786f11c0a1ce950802a3a78279863b1df0b/README.md#bindings)
> Unify and clean the unofficial project references

- resources/boundaries/osm/ar.yaml
- resources/boundaries/osm/tw.yaml
fix 2 small format errors in the file:
* add missing "relation" tag for buenos aires
* overrides shouldn't be nested in admin_level, but should be at the top level
> Fix small problems in osm boundaries files

- src/libpostal.c
I found this leak when passing an invalid datadir to setup. I'm running on 1.0.0 but it seems this issue still exists on master:
```
ERR   Error loading transliteration module, dir=/fake/datadir/transliteration/transliteration.dat
at libpostal_setup_datadir (libpostal.c:1047) errno: No such file or directory
WARNING: Logging before InitGoogleLogging() is written to STDERR
ERR   parser is not setup, call libpostal_setup_address_parser()
at address_parser_parse (address_parser.c:1659) errno: No such file or directory
ERR   Parser returned NULL
at libpostal_parse_address (libpostal.c:1027) errno: No such file or directory
=================================================================
==4194251==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 128 byte(s) in 1 object(s) allocated …
```
> fix memory leak in setup when datadir is invalid or setup failed

- resources/addresses/de.yaml
- resources/addresses/uk.yaml
> Fixed a typo in Ukrainian transliterated word 'budynok' (house). Added German geb prefix

- scripts/geodata/neighborhoods/reverse_geocode.py
- scripts/geodata/polygons/index.py
- scripts/geodata/whosonfirst/download_wof_admin_polygon.py
- replace quattroshapes polygons with whosonfirst polygons (as the quattroshapes files are no longer available, and the author points queriers to whosonfirst, see https://github.com/foursquare/quattroshapes/issues/10)
> whosonfirst neighbourhood reverse geocoder

- README.md
libpostal can be installed in one shot via MacPorts.
> Mention install with MacPorts in readme

- resources/dictionaries/ro/personal_titles.txt
I noticed `expand_address` does not expand "g-ral" to "general".
Although I couldn't find an official source for this, a lot of street name signs in Romania abbreviate "General" as "G-ral". People also often abbreviate it like this in all kinds of writing.
* [Strada General Constantin Budișteanu, Bucharest](https://goo.gl/maps/HqGKGfn15JXYG3PbA)
* [Strada General Gheorghe Manu, Bucharest](https://goo.gl/maps/FgdvY33fSXfZpa7S8)
* [Strada General Christian Tell, Bucharest](https://goo.gl/maps/d8rM1tSff5oWqNNEA)
* [Bulevardul General Vasile Milea, Sibiu](https://goo.gl/maps/UcU2eLy11wGmYvEF9)
etc.
> Consider expanding "g-ral" to "general" in Romanian street names

- README.md
Replace broken link to http://blog.echen.me/2012/01/03/introduction-to-conditional-random-fields/ by link to latest valid webarchive version at https://web.archive.org/web/20240104172655/http://blog.echen.me/2012/01/03/introduction-to-conditional-random-fields/
Note that math is not rendered in the webarchive version, but at least it's not 404.
Tagging blog post creator Erwin Chen @echen for awareness (thanks for your blog post 😊).
> Fix broken blog post link in README

- scripts/geodata/i18n/transliteration_rules.py
These regex may cause exponential backtracking on strings starting with '\[\[\]' and containing many repetitions of 'Z\[\]'. 
There is no active usage of these regex in the code, removing it as a precaution to avoid any future uses.
From copilot for more context, such regular expressions can negatively affect performance, or even allow a malicious user to perform a Denial of Service  attack by crafting an expensive input string for the regular expression to match. The regular expression engine provided by Python uses a backtracking non-deterministic finite automata to implement regular expression matching. While this approach is space-efficient and allows supporting advanced features like capture groups, it is not time-efficient in general .
> Remove unused regex that can cause exponential backtracking when used

- configure.ac
In some cases `uname -m` returns `aarch64` rather than `arm64` for arm CPUs.
This PR should let libpostal build correctly in those cases. 
PR is based on this one for apple silicon support: https://github.com/openvenues/libpostal/pull/679
> Support more arm processors

- src/normalize.c
- src/numex.c
- src/string_utils.c
- src/transliterate.c
- src/trie_search.c
- src/unicode_scripts.c
Reviewed and fixed all points where utf8proc_iterate is called and may return an error which can cause the iteration not to make forward progress. This includes fixing a bug where injecting invalid UTF-8 through a series of HTML-encoded codepoints can cause the C library to hang. Note: we're not fixing all the garbage encoding in the world, so if encoding is bad the output of expand_address may not be useful but it won't hang. Fixes #448
> Error-checking for all utf8proc_iterate calls where invalid UTF-8 (or injection of same via HTML entities) may cause loops not to terminate
