README.md

Add curl to dependency list for Ubuntu build

Add curl dependancy for Ubuntu

---

resources/dictionaries/en/place_names.txt
resources/dictionaries/en/post_office.txt
resources/dictionaries/en/stopwords.txt
resources/dictionaries/en/street_types.txt
resources/dictionaries/en/unit_types.txt

I've been using an ugly custom python script to do this parsing until now, so here's some missing entries I've built up from Australian addresses from my custom scripts.

Add some missing AU dictionary entries

---

resources/dictionaries/eu/place_names.txt

I've made some changes to the build for #15 that should make the process of contributing abbreviations simpler (just edit text files as in this PR). If everything is working correctly, this should build and test the changes, but not push any files until it is merged into master.

Testing dictionaries pull request

---

README.md

Added link to @pramsey's Postgres bindings in the README.md.

add postgres binding info

---

resources/dictionaries/it/street_types.txt

add new annotations for the italian street dictionary

new annotation for italian street dict

---

resources/dictionaries/it/street_types.txt

add new abbreviations porto, add annotation for traversa, vico, traversa nuova, traversa privata, traversa vicinale, zona industriale

add new abbreviations

---

resources/dictionaries/it/street_types.txt
resources/dictionaries/it/unit_types.txt

add new annotations for 'strada provinciale' and 'strada statale'

add new annotations

---

bootstrap.sh
src/libpostal_data

This is a resubmission of my previous pull request because I don't (yet) know a better way to sync current/master.

Use posix `sh` for systems without `bash`

---

src/address_parser_io.c
src/address_parser_test.c
src/address_parser_train.c
src/string_utils.c
src/string_utils.h
src/tokens.c

Fix address_parser_train

---

src/Makefile.am
src/sparkey/Makefile.am

Have to do a Makefile dance to make sure scanner.c compiles with ```-O0```, regardless of what the user passed in, otherwise it will take an unreasonable amount of time.

Allow user to pass in CFLAGS

---

resources/dictionaries/be/place_names.txt
resources/dictionaries/ru/place_names.txt

These all are parts of streets.

Remove place names that are not place names (RU, BE)

---

resources/dictionaries/cy/building_types.txt
resources/dictionaries/cy/directionals.txt
resources/dictionaries/cy/place_names.txt

As a native Welsh speaker I've updated some of the Welsh language dictionaries to fill in some omissions.

Enhanced the Welsh (cy) language dictionaries.

---

README.md

Hi all, We have been using awesome libpostal lib with zeromq. Thought I would share this.

Update ReadME to add ZeroMQ docker app

---

src/string_utils.c

Remove unused variable

---

.travis.yml
resources/numex/es.yaml
resources/numex/it.yaml
test/test_expand.c

fix to numex change detection in Travis config

Ordinal suffix tests

---

resources/dictionaries/en/building_types.txt

I noticed this was missing while testing a batch of addresses. Hopefully it doesn't introduce much noise.
I think the last line diff is because either git doesn't play nice with files not ending in a blank line.

Add 'bld' as an abbreviation for 'building'

---

resources/dictionaries/en/toponyms.txt

Trivial. Just one line adding a common toponym for "Melbourne"

melbourne city toponym

---

README.md

 Added unofficial Java language binding

---

src/klib/drand48.h

This is a fix for build issues on windows.

#501. Fixed build issues on MSYS on Windows.

---

CONTRIBUTING.md

Respect typo

---

src/matrix.h
src/vector.h

Fixes #639 tests passing, waiting for confirmation on real data

Fix aligned resize

---

ISSUE_TEMPLATE.md

[docs] fix minor typo

---

README.md

Updates Readme to reflect the position of the project on address extraction from free text. The question has risen several times and It could be a good idea to reflect that it is not on the scope up front.
Source:
https://github.com/openvenues/libpostal/issues/22

[docs] Update Readme.md on free text extraction

---

resources/dictionaries/en/street_types.txt

Common in Texas.  Here's an example in OSM:
https://www.openstreetmap.org/relation/3016442#map=12/30.5562/-97.4764

Adding farm to market street type

---

resources/dictionaries/pt/street_types.txt

Correction to mispelling of "estrada" and addition of abbreviation "dt" for "direito"

Update street_types.txt for Portuguese language

---

resources/dictionaries/es/street_types.txt

I'm grouping boulevard synonyms in spanish and adding a new one (br)

group synonyms
